language: php

php:
  - 5.5
  - 5.6
  - 7

before_script:
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require zendframework/zendframework:^2.5 netiul/dompdf-module:dev-master
  - cp ../.travis/application.config.php config/application.config.php

script:
  - vendor/bin/phpunit --configuration vendor/netiul/dompdf-module/tests/phpunit.xml vendor/netiul/dompdf-module/tests
