name: "Continuous Integration"

on: ["pull_request"]

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        php-version:
          - "7.4"
        deps:
          - "lowest"
          - "highest"
        include:
          - php-version: "8.0"
            deps: "highest"
            experimental: true

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.deps }}"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
